[tool.black]
line-length = 99
target-version = ["py38", "py39", "py310", "py311", "py312"]

[tool.isort]
profile = "black"
line_length = 99

[tool.mypy]
mypy_path = "$MYPY_CONFIG_FILE_DIR/typings"

[tool.setuptools]
packages = ["dogscogs"]