from ..constants import TIMEZONE as TIMEZONE
from _typeshed import Incomplete
from collections.abc import Generator
from datetime import datetime as datetime

def date_formats() -> Generator[Incomplete, None, None]: ...
def to_birthdate(*args, **kwargs): ...
def duration_string(hours: int, minutes: int, seconds: int) -> str: ...
def parse_duration_string(input: str) -> int: ...
