import discord
from redbot.core import Config as Config

async def validate_true(str: str, interaction: discord.Interaction): ...
async def validate_number_or_diceroll(input: str, interaction: discord.Interaction): ...
async def validate_percent_or_diceroll(input: str, interaction: discord.Interaction): ...
async def validate_not_in_list(list: list[str], input: str, interaction: discord.Interaction): ...
async def validate_image(input: str, _interaction: discord.Interaction): ...
async def validate_length(length: int, input: str, interaction: discord.Interaction): ...
