from _typeshed import Incomplete
from fractions import Fraction
from typing import Iterable

HSVTuple = tuple[Fraction, Fraction, Fraction]
RGBTuple = tuple[float, float, float]
DEFAULT_COLORS: Incomplete

def color_diff(rgb1, rgb2): ...
def sort_palette(color): ...
def aggregate_palette(p): ...
def min_palette_diff(p): ...
def get_palette(n: int = 100, Lmin: int = 5, Lmax: int = 90, maxLoops: int = 100000) -> Iterable[RGBTuple]: ...
def hex_to_rgb(h: str) -> tuple[int, int, int]: ...
