import discord
import typing
from _typeshed import Incomplete

async def async_true(i: discord.Interaction) -> bool: ...

class ConfirmationView(discord.ui.View):
    value: bool
    author: Incomplete
    callback: Incomplete
    def __init__(self, *, author: discord.Member, callback: typing.Callable[[discord.Interaction], typing.Awaitable[bool]] = ...) -> None: ...
    async def interaction_check(self, interaction: discord.Interaction) -> bool: ...
    async def yes(self, interaction: discord.Interaction, button: discord.ui.Button): ...
    async def no(self, interaction: discord.Interaction, button: discord.ui.Button): ...
